/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ClsConexion;

/**
 *
 * @author Juan Porras
 */
public class FrmIndex extends javax.swing.JFrame {

    /**
     * Creates new form FrmIndex
     */
    public FrmIndex() {
        initComponents();
    }

//Metodos
    public void estudiante() {
        FrmEstudiante objFrmEstudiante = new FrmEstudiante();
        objFrmEstudiante.setVisible(true);
        this.dispose();
    }

    public void acudiente() {
        FrmAcudiente objFrmAcudiente = new FrmAcudiente();
        objFrmAcudiente.setVisible(true);
        this.dispose();
    }

    public void profesor() {
        FrmProfesor objFrmProfesor = new FrmProfesor();
        objFrmProfesor.setVisible(true);
        this.dispose();
    }

    public void materia() {
        FrmMateria objFrmMateria = new FrmMateria();
        objFrmMateria.setVisible(true);
        this.dispose();
    }

    public void conexion() {
        ClsConexion objClsConexion = new ClsConexion();
        objClsConexion.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnEst = new javax.swing.JButton();
        BtnAcu = new javax.swing.JButton();
        BtnProCon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnPro = new javax.swing.JButton();
        BtnMat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        BtnEst.setText("Estudiante");
        BtnEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstActionPerformed(evt);
            }
        });

        BtnAcu.setText("Acudiente");
        BtnAcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAcuActionPerformed(evt);
            }
        });

        BtnProCon.setText("Probar conexion");
        BtnProCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProConActionPerformed(evt);
            }
        });

        BtnPro.setText("Profesor");
        BtnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProActionPerformed(evt);
            }
        });

        BtnMat.setText("Materia");
        BtnMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnPro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAcu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnEst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnProCon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BtnEst)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAcu)))
                .addGap(18, 18, 18)
                .addComponent(BtnPro)
                .addGap(18, 18, 18)
                .addComponent(BtnMat)
                .addGap(18, 18, 18)
                .addComponent(BtnProCon)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstActionPerformed
        this.estudiante();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEstActionPerformed

    private void BtnAcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAcuActionPerformed
        this.acudiente();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAcuActionPerformed

    private void BtnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProActionPerformed
        this.profesor();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProActionPerformed

    private void BtnMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMatActionPerformed
        this.materia();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMatActionPerformed

    private void BtnProConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProConActionPerformed
this.conexion();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAcu;
    private javax.swing.JButton BtnEst;
    private javax.swing.JButton BtnMat;
    private javax.swing.JButton BtnPro;
    private javax.swing.JButton BtnProCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
