/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ClsConexion;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.ClsRegistroUsuario;

/**
 *
 * @author Juan Porras
 */
public class FrmIndex extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
//    private FrmRegistroUsuario registroUsuario;
    public FrmIndex() {
        initComponents();
    }

//Declaracion de variables
    ClsRegistroUsuario objClsRegistroUsuario = new ClsRegistroUsuario();

//Metodos
    public void capturar() {
        objClsRegistroUsuario.setIdUsuRegUsu(FrmRegistroUsuario.DocumentoUsuario);
        objClsRegistroUsuario.setFecHoraCieRegUsu(TxtFecHoraCieRegUsu.getText());
        objClsRegistroUsuario.setTieTotRegUsu(TxtTieTotRegUsu.getText());
    }

    public void FechaHoraCer() {
        Date FechaHoraActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String CadenaFechaHora = formato.format(FechaHoraActual);
        TxtFecHoraCieRegUsu.setText("" + CadenaFechaHora);
    }

    public void ProbarConexion() {
        ClsConexion objClsConexion = new ClsConexion();
        objClsConexion.conectar();
    }

    public void usuario() {
        FrmUsuario objFrmUsuario = new FrmUsuario();
        objFrmUsuario.setVisible(true);
        this.dispose();
    }

    public void cliente() {
        FrmCliente objFrmCliente = new FrmCliente();
        objFrmCliente.setVisible(true);
        this.dispose();
    }

    public void campana() {
        FrmCampaña objFrmCampaña = new FrmCampaña();
        objFrmCampaña.setVisible(true);
        this.dispose();
    }

    public void AsignacionLlamada() {
        FrmAsignacionLlamada objFrmAsignacionLlamada = new FrmAsignacionLlamada();
        objFrmAsignacionLlamada.setVisible(true);
        this.dispose();
    }

    public void interaccion() {
        FrmInteraccion objFrmInteraccion = new FrmInteraccion();
        objFrmInteraccion.setVisible(true);
        this.dispose();
    }

    public void asesor() {
        FrmAsesor objFrmAsesor = new FrmAsesor();
        objFrmAsesor.setVisible(true);
        this.dispose();
    }

    public void RegistroTiempos() {
        FrmRegistroTiempos objFrmRegistroTiempos = new FrmRegistroTiempos();
        objFrmRegistroTiempos.setVisible(true);
        this.dispose();
    }

    public void CerrarSesion() {
        try {
            this.FechaHoraCer();
            this.capturar();
            objClsRegistroUsuario.CerrarSesion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fallas Tecnicas al cerrar sesion : " + e);
        }
    }

    public void RegistroUsuario() {
        FrmRegistroUsuario objFrmRegistroUsuario = new FrmRegistroUsuario();
        objFrmRegistroUsuario.setVisible(true);
        this.dispose();
    }

    public void PanelSupervisor() {
        FrmPanelSupervisor objFrmPanelSupervisor = new FrmPanelSupervisor();
        objFrmPanelSupervisor.setVisible(true);
        this.dispose();
    }

    public void IndicadoresGestion() {
        FrmIndicadoresGestion objFrmIndicadoresGestion = new FrmIndicadoresGestion();
        objFrmIndicadoresGestion.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TxtTieTotRegUsu = new javax.swing.JTextField();
        TxtFecHoraCieRegUsu = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnUsu = new javax.swing.JButton();
        BtnCli = new javax.swing.JButton();
        BtnCam = new javax.swing.JButton();
        BtnAsiLla = new javax.swing.JButton();
        BtnInt = new javax.swing.JButton();
        BtnCas = new javax.swing.JButton();
        BtnCam1 = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BtnPanSup = new javax.swing.JButton();
        BtnIndGes = new javax.swing.JButton();

        TxtTieTotRegUsu.setEditable(false);

        TxtFecHoraCieRegUsu.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Index");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Index");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        BtnUsu.setBackground(new java.awt.Color(51, 51, 255));
        BtnUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnUsu.setText("Usuario");
        BtnUsu.setToolTipText("");
        BtnUsu.setBorderPainted(false);
        BtnUsu.setContentAreaFilled(false);
        BtnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuActionPerformed(evt);
            }
        });

        BtnCli.setBackground(new java.awt.Color(51, 51, 255));
        BtnCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnCli.setText("Cliente");
        BtnCli.setToolTipText("");
        BtnCli.setBorderPainted(false);
        BtnCli.setContentAreaFilled(false);
        BtnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCliActionPerformed(evt);
            }
        });

        BtnCam.setBackground(new java.awt.Color(51, 51, 255));
        BtnCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnCam.setText("Campaña");
        BtnCam.setToolTipText("");
        BtnCam.setBorderPainted(false);
        BtnCam.setContentAreaFilled(false);
        BtnCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCamActionPerformed(evt);
            }
        });

        BtnAsiLla.setBackground(new java.awt.Color(51, 51, 255));
        BtnAsiLla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnAsiLla.setText("Asignacion de llamadas");
        BtnAsiLla.setToolTipText("");
        BtnAsiLla.setBorderPainted(false);
        BtnAsiLla.setContentAreaFilled(false);
        BtnAsiLla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsiLlaActionPerformed(evt);
            }
        });

        BtnInt.setBackground(new java.awt.Color(51, 51, 255));
        BtnInt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnInt.setText("Interaccion");
        BtnInt.setToolTipText("");
        BtnInt.setBorderPainted(false);
        BtnInt.setContentAreaFilled(false);
        BtnInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIntActionPerformed(evt);
            }
        });

        BtnCas.setBackground(new java.awt.Color(51, 51, 255));
        BtnCas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnCas.setText("Asesor");
        BtnCas.setToolTipText("");
        BtnCas.setBorderPainted(false);
        BtnCas.setContentAreaFilled(false);
        BtnCas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCasActionPerformed(evt);
            }
        });

        BtnCam1.setBackground(new java.awt.Color(51, 51, 255));
        BtnCam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnCam1.setText("Registro tiempos");
        BtnCam1.setToolTipText("");
        BtnCam1.setBorderPainted(false);
        BtnCam1.setContentAreaFilled(false);
        BtnCam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCam1ActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(0, 51, 255));
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cer.png"))); // NOI18N
        BtnSalir.setText("Cerrar sesion");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnPanSup.setBackground(new java.awt.Color(51, 51, 255));
        BtnPanSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnPanSup.setText("Panel supervisor");
        BtnPanSup.setToolTipText("");
        BtnPanSup.setBorderPainted(false);
        BtnPanSup.setContentAreaFilled(false);
        BtnPanSup.setName(""); // NOI18N
        BtnPanSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanSupActionPerformed(evt);
            }
        });

        BtnIndGes.setBackground(new java.awt.Color(51, 51, 255));
        BtnIndGes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sig.png"))); // NOI18N
        BtnIndGes.setText("Indicadores de gestion");
        BtnIndGes.setToolTipText("");
        BtnIndGes.setBorderPainted(false);
        BtnIndGes.setContentAreaFilled(false);
        BtnIndGes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIndGesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnIndGes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnUsu)
                            .addComponent(BtnCam)
                            .addComponent(BtnCam1)
                            .addComponent(BtnCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCas)
                            .addComponent(BtnAsiLla)
                            .addComponent(BtnInt)
                            .addComponent(BtnPanSup))
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(477, 477, 477))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnSalir)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUsu)
                    .addComponent(BtnCas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCli)
                    .addComponent(BtnAsiLla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCam)
                    .addComponent(BtnInt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCam1)
                    .addComponent(BtnPanSup))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnIndGes)
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addComponent(BtnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuActionPerformed
        this.usuario();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUsuActionPerformed

    private void BtnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCliActionPerformed
        this.cliente();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCliActionPerformed

    private void BtnCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCamActionPerformed
        this.campana();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCamActionPerformed

    private void BtnAsiLlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsiLlaActionPerformed
        this.AsignacionLlamada();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAsiLlaActionPerformed

    private void BtnIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIntActionPerformed
        this.interaccion();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIntActionPerformed

    private void BtnCasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCasActionPerformed
        this.asesor();// TODO add your handling code here:
    }//GEN-LAST:event_BtnCasActionPerformed

    private void BtnCam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCam1ActionPerformed
        this.RegistroTiempos();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCam1ActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        this.CerrarSesion();
        this.RegistroUsuario();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnPanSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanSupActionPerformed
        this.PanelSupervisor();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPanSupActionPerformed

    private void BtnIndGesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIndGesActionPerformed
        this.IndicadoresGestion();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIndGesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAsiLla;
    private javax.swing.JButton BtnCam;
    private javax.swing.JButton BtnCam1;
    private javax.swing.JButton BtnCas;
    private javax.swing.JButton BtnCli;
    private javax.swing.JButton BtnIndGes;
    private javax.swing.JButton BtnInt;
    private javax.swing.JButton BtnPanSup;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnUsu;
    private javax.swing.JTextField TxtFecHoraCieRegUsu;
    private javax.swing.JTextField TxtTieTotRegUsu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
