/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.ClsRegistrarAnimales;

/**
 *
 * @author Juan Porras
 */
public class FrmRegistrarAnimales extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarAnimales
     */
    public FrmRegistrarAnimales() {
        initComponents();
        this.consecutivo();
    }

//Declaracion de variables
    ClsRegistrarAnimales objClsRegistrarAnimales = new ClsRegistrarAnimales();

//Metodos
    public void capturar() {
        objClsRegistrarAnimales.setCodigo(Integer.parseInt(Txt_codigo.getText()));
        objClsRegistrarAnimales.setCategoria(Cbo_categoria.getSelectedItem().toString());
        objClsRegistrarAnimales.setRaza(Cbo_raza.getSelectedItem().toString());
        objClsRegistrarAnimales.setColor(Txt_color.getText());
        objClsRegistrarAnimales.setTamaño(Float.parseFloat(Txt_tamaño.getText()));
        objClsRegistrarAnimales.setGenero(Cbo_genero.getSelectedItem().toString());
        objClsRegistrarAnimales.setNombre(Txt_nombre.getText());
    }

    public void limpiar() {
        Txt_codigo.setText(null);
        Cbo_categoria.setSelectedIndex(0);
        Cbo_raza.setSelectedIndex(0);
        Txt_color.setText(null);
        Txt_tamaño.setText(null);
        Cbo_genero.setSelectedIndex(0);
        Txt_nombre.setText(null);
    }

    public void consecutivo() {
        objClsRegistrarAnimales.consecutivo();
        try {
            if (objClsRegistrarAnimales.DatosConsecutivo.next()) {
                Txt_codigo.setText(objClsRegistrarAnimales.DatosConsecutivo.getString(1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se puede generar el codigo: " + e);
        }
    }

    public void NombreRaza() {
        if (Cbo_categoria.getSelectedIndex() == 1) {
            Cbo_raza.removeAllItems();
            Cbo_raza.addItem("Seleccione...");
            Cbo_raza.addItem("Blanco oreginegro");
            Cbo_raza.addItem("Chino santandereano");
            Cbo_raza.addItem("Costeño con cuernos");
            Cbo_raza.addItem("Harton del valle");
        } else if (Cbo_categoria.getSelectedIndex() == 2) {
            Cbo_raza.removeAllItems();
            Cbo_raza.addItem("Seleccione...");
            Cbo_raza.addItem("Pura sangre");
            Cbo_raza.addItem("Andalucia");
            Cbo_raza.addItem("Percheron");
        } else if (Cbo_categoria.getSelectedIndex() == 3) {
            Cbo_raza.removeAllItems();
            Cbo_raza.addItem("Seleccione...");
            Cbo_raza.addItem("Duroc Jersey");
            Cbo_raza.addItem("Pietran");
            Cbo_raza.addItem("Landrace");
            Cbo_raza.addItem("Yorkshire");
        } else {
            Cbo_raza.removeAllItems();
            Cbo_raza.addItem("Seleccione...");
        }
    }

    public void guardar() {
        this.capturar();
        objClsRegistrarAnimales.guardar();
        this.limpiar();
        this.consecutivo();
    }

    public void regresar() {
        FrmMenu objFrmMenu = new FrmMenu();
        objFrmMenu.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_codigo = new javax.swing.JTextField();
        Cbo_categoria = new javax.swing.JComboBox<>();
        Cbo_raza = new javax.swing.JComboBox<>();
        Txt_nombre = new javax.swing.JTextField();
        Btn_regresar = new javax.swing.JButton();
        Btn_guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Txt_color = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_tamaño = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cbo_genero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar animales");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Animales");

        jLabel2.setText("Codigo");

        jLabel3.setText("Categoria");

        jLabel4.setText("Raza");

        jLabel5.setText("Nombre");

        Txt_codigo.setEditable(false);

        Cbo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la categoria...", "Bovinos", "Equinos", "Porcinos" }));
        Cbo_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbo_categoriaActionPerformed(evt);
            }
        });

        Cbo_raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la raza a partir de la categoria..." }));

        Btn_regresar.setBackground(new java.awt.Color(153, 153, 153));
        Btn_regresar.setText("Regresar");
        Btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_regresarActionPerformed(evt);
            }
        });

        Btn_guardar.setBackground(new java.awt.Color(153, 153, 153));
        Btn_guardar.setText("Guardar");
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });

        jLabel6.setText("Color");

        jLabel7.setText("Tamaño");

        jLabel8.setText("Genero");

        Cbo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Masculino", "Femenino" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_regresar)
                .addGap(18, 18, 18)
                .addComponent(Btn_guardar)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cbo_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cbo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_nombre)))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cbo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cbo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cbo_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Cbo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_regresar)
                    .addComponent(Btn_guardar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cbo_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbo_categoriaActionPerformed
        this.NombreRaza();        // TODO add your handling code here:
    }//GEN-LAST:event_Cbo_categoriaActionPerformed

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
        this.guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_guardarActionPerformed

    private void Btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_regresarActionPerformed
        this.regresar();        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarAnimales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JButton Btn_regresar;
    private javax.swing.JComboBox<String> Cbo_categoria;
    private javax.swing.JComboBox<String> Cbo_genero;
    private javax.swing.JComboBox<String> Cbo_raza;
    private javax.swing.JTextField Txt_codigo;
    private javax.swing.JTextField Txt_color;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JTextField Txt_tamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
