/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.ClsMasaCorporal;

/**
 *
 * @author Juan Porras
 */
public class FrmIndex extends javax.swing.JFrame {

    /**
     * Creates new form FrmIndex
     */
    public FrmIndex() {
        initComponents();
    }

//Metodos
    public void Suma2Numeros() {
        FrmSuma2Numeros objFrmSuma2Numeros = new FrmSuma2Numeros();
        objFrmSuma2Numeros.setVisible(true);
        this.dispose();
    }

    public void MasaCorporal() {
        FrmMasaCorporal objFrmMasaCorporal = new FrmMasaCorporal();
        objFrmMasaCorporal.setVisible(true);
        this.dispose();
    }

    public void CapitalObtenidoInversion() {
        FrmCapitalObtenidoInversion objFrmCapitalObtenidoInversion = new FrmCapitalObtenidoInversion();
        objFrmCapitalObtenidoInversion.setVisible(true);
        this.dispose();
    }

    public void CantidadHombresMujeres() {
        FrmCantidadHombresMujeres objFrmCantidadHombresMujeres = new FrmCantidadHombresMujeres();
        objFrmCantidadHombresMujeres.setVisible(true);
        this.dispose();
    }

    public void CalcularSalarioNuevo() {
        FrmCalcularSalarioNuevo objFrmcalcularSalarioNuevo = new FrmCalcularSalarioNuevo();
        objFrmcalcularSalarioNuevo.setVisible(true);
        this.dispose();
    }

    public void CalcularDefinitiva() {
        FrmCalcularDefinitiva objFrmCalcularDefinitiva = new FrmCalcularDefinitiva();
        objFrmCalcularDefinitiva.setVisible(true);
        this.dispose();
    }

    public void AreaTriangulo() {
        FrmAreaTriangulo objFrmAreaTriangulo = new FrmAreaTriangulo();
        objFrmAreaTriangulo.setVisible(true);
        this.dispose();
    }

    public void AreaRectangulo() {
        FrmAreaRectangulo objFrmAreaRectangulo = new FrmAreaRectangulo();
        objFrmAreaRectangulo.setVisible(true);
        this.dispose();
    }

    public void CalculosMatematicos() {
        FrmCalculosMatematicos objFrmCalculosMatematicos = new FrmCalculosMatematicos();
        objFrmCalculosMatematicos.setVisible(true);
        this.dispose();
    }

 public void AreaFiguras() {
        FrmAreaFiguras objFrmAreaFiguras = new FrmAreaFiguras();
        objFrmAreaFiguras.setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnSuma = new javax.swing.JButton();
        BtnMasaCorporal = new javax.swing.JButton();
        BtnCantidadPersonas = new javax.swing.JButton();
        BtnInversion = new javax.swing.JButton();
        BtnDefinitiva = new javax.swing.JButton();
        BtnSalario = new javax.swing.JButton();
        BtnAreaTriangulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnAreaRectangulo = new javax.swing.JButton();
        BtnCalculosMatematicos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BtnAreaFiguras = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario menu principal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Index");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        BtnSuma.setText("Ir");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnMasaCorporal.setText("Ir");
        BtnMasaCorporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMasaCorporalActionPerformed(evt);
            }
        });

        BtnCantidadPersonas.setText("Ir");
        BtnCantidadPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCantidadPersonasActionPerformed(evt);
            }
        });

        BtnInversion.setText("Ir");
        BtnInversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInversionActionPerformed(evt);
            }
        });

        BtnDefinitiva.setText("Ir");
        BtnDefinitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDefinitivaActionPerformed(evt);
            }
        });

        BtnSalario.setText("Ir");
        BtnSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalarioActionPerformed(evt);
            }
        });

        BtnAreaTriangulo.setText("Ir");
        BtnAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaTrianguloActionPerformed(evt);
            }
        });

        jLabel1.setText("Suma");

        jLabel2.setText("Masa corporal");

        jLabel3.setText("Inversion");

        jLabel4.setText("Cantidad personas");

        jLabel6.setText("Salario");

        jLabel7.setText("Definitiva");

        jLabel8.setText("Area triangulo");

        jLabel9.setText("Area rectangulo");

        BtnAreaRectangulo.setText("Ir");
        BtnAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaRectanguloActionPerformed(evt);
            }
        });

        BtnCalculosMatematicos.setText("Ir");
        BtnCalculosMatematicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalculosMatematicosActionPerformed(evt);
            }
        });

        jLabel11.setText("Calculos matemaicos");

        BtnAreaFiguras.setText("Ir");
        BtnAreaFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAreaFigurasActionPerformed(evt);
            }
        });

        jLabel12.setText("Area figuras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnCalculosMatematicos)
                    .addComponent(BtnSuma)
                    .addComponent(BtnMasaCorporal)
                    .addComponent(BtnInversion)
                    .addComponent(BtnCantidadPersonas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnDefinitiva)
                            .addComponent(BtnAreaTriangulo)
                            .addComponent(BtnAreaRectangulo)
                            .addComponent(BtnSalario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAreaFiguras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSuma)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnMasaCorporal)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(BtnInversion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(BtnCantidadPersonas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(BtnSalario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(BtnDefinitiva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(BtnAreaTriangulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAreaRectangulo)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalculosMatematicos)
                    .addComponent(jLabel11)
                    .addComponent(BtnAreaFiguras)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        this.Suma2Numeros();     // TODO add your handling code here:
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnCantidadPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCantidadPersonasActionPerformed
        this.CantidadHombresMujeres();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCantidadPersonasActionPerformed

    private void BtnMasaCorporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMasaCorporalActionPerformed
        this.MasaCorporal();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMasaCorporalActionPerformed

    private void BtnInversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInversionActionPerformed
        this.CapitalObtenidoInversion();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInversionActionPerformed

    private void BtnSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalarioActionPerformed
        this.CalcularSalarioNuevo();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalarioActionPerformed

    private void BtnDefinitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDefinitivaActionPerformed
        this.CalcularDefinitiva();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDefinitivaActionPerformed

    private void BtnAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaTrianguloActionPerformed
        this.AreaTriangulo();// TODO add your handling code here:
    }//GEN-LAST:event_BtnAreaTrianguloActionPerformed

    private void BtnAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaRectanguloActionPerformed
        this.AreaRectangulo();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAreaRectanguloActionPerformed

    private void BtnCalculosMatematicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalculosMatematicosActionPerformed
this.CalculosMatematicos();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCalculosMatematicosActionPerformed

    private void BtnAreaFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAreaFigurasActionPerformed
this.AreaFiguras();        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAreaFigurasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAreaFiguras;
    private javax.swing.JButton BtnAreaRectangulo;
    private javax.swing.JButton BtnAreaTriangulo;
    private javax.swing.JButton BtnCalculosMatematicos;
    private javax.swing.JButton BtnCantidadPersonas;
    private javax.swing.JButton BtnDefinitiva;
    private javax.swing.JButton BtnInversion;
    private javax.swing.JButton BtnMasaCorporal;
    private javax.swing.JButton BtnSalario;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
